---
- name: 'Update APT'
  tags:
    - 'rabbitmq'
    - 'apt'
  sudo: 'yes'
  apt: update_cache=yes
  
- name: 'Ensure python-software-properties is installed'
  tags:
    - 'rabbitmq'
    - 'python'
  sudo: 'yes'
  apt: pkg=python-software-properties state=installed

- name: 'Add rabbitmq to APT repository'
  tags:
    - 'rabbitmq'
    - 'apt'
  sudo: 'yes'
  apt_repository: >
    repo='deb http://www.rabbitmq.com/debian/ testing main'
    state=present

- name: 'Install rabbitmq'
  tags: 'rabbitmq'
  sudo: 'yes'
  apt: >
    pkg=rabbitmq-server state=installed
    force=yes

- name: 'Enable rabbitmq plugins'
  tags: 'rabbitmq'
  sudo: 'yes'
  rabbitmq_plugin: >
    names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state=enabled
  register: enable_rabbitmq_plugins_result

  # MUST RESTART SERVER AFTER ENABLING PLUGINS
- name: 'Restart rabbitmq'
  tags: 'rabbitmq'
  sudo: 'yes'
  service: >
    name=rabbitmq-server
    state=restarted
  when: enable_rabbitmq_plugins_result.changed
  
- name: 'Add administrators'
  tags: 'rabbitmq'
  sudo: 'yes'
  rabbitmq_user: >
    user={{ item }}
    password={{rabbitmq_password}}
    tags=administrator,{{ item }}
    vhost=/
    configure_priv=.*
    write_priv=.*
    read_priv=.*
    state=present
  with_items:
  - "{{ rabbitmq_user }}"

- name: 'Remove default guest user'
  tags: 'rabbitmq'
  sudo: 'yes'
  rabbitmq_user: >
    user=guest
    state=absent